### ISSUE TITLE
Use `dart:ffi` instead of included binary

### ISSUE THREAD

**Issue by ardera** [CanonicalLtd/unix_domain_socket.dart#2]
First of all this is a nice project.

But right now this only supports 1 architecture, more precisely the one on which the included `libunix_domain_socket.so` is compiled.

When using `dart:ffi` on the other hand, support for multiple architectures is trivial. Even though, right now, there's a lot of boilerplate code involved (especially for inline arrays) when using `dart:ffi`, I still think it's better.

What do you think?

I'd be willing to contribute if you agree.

**Comment by MarcusTomlinson** [comment]
Hey @ardera, yeah fully agree! If you’d like to take a stab at it, that’d be great.

**Comment by MarcusTomlinson** [comment]
Now that standard unix domain sockets are available from dart:io, this project is no longer needed, and thus no longer maintained.
