### ISSUE TITLE
Doesn't fail until reads if socket doesn't exist

### ISSUE THREAD

**Issue by Wazzaps** [CanonicalLtd/unix_domain_socket.dart#3]
This was annoying to debug...
In my machine, `$DBUS_SESSION_BUS_ADDRESS` is equal to `unix:path=/run/user/1000/bus` in vscode, but `unix:path=/run/user/1000/bus,guid=f114316a6facbc740a8cdaf25f0b84aa` in the terminal emulator!
I have no idea what the cause is, but I'll thank strace for saving me here.

Anyway, reading from a socket that opened an invalid path (`/run/user/1000/bus,guid=f114316a6facbc740a8cdaf25f0b84aa` in this case) gives a red herring:
`flutter: Failed to read from socket: Invalid argument`

That's because `connect` failed! We should throw an exception there.
Also the whole `errno` design is flawed, because the `errno` is shared between us and dart, so:
```dart
    // -- A read operation --
    int readCount = readP(_fd, bufferP, len);  // <-- we want to capture the errno of this

    // -- Get errno for read operation --
    // <bad>
    DynamicLibrary dylib;
    try {
      Packages packages = new Packages();
      Package package = packages.resolvePackageUri(Uri.parse("package:unix_domain_socket"));
      dylib = DynamicLibrary.open(package.lib.path + '/libunixdomainsocket.so');
    } catch (e) {
      dylib = DynamicLibrary.open('libunixdomainsocket.so');
    }
    // </bad>  <-- All of this may change the errno

    final getErrorP = dylib.lookupFunction<_GetErrorC, _GetErrorDart>('UnixDomainSocket_GetError');
```

**Comment by MarcusTomlinson** [comment]
Now that standard unix domain sockets are available from dart:io, this project is no longer needed, and thus no longer maintained.
